-- ============================================================
-- TAMU CSEGSA Hackathon 2026 — Snowflake Setup Script
-- Run each step one at a time (select block, click Run)
-- ============================================================

-- *** STEP 1: Run this first ***
CREATE DATABASE IF NOT EXISTS HACKATHON;

-- *** STEP 2: Run this ***
CREATE SCHEMA IF NOT EXISTS HACKATHON.DATA;

-- *** STEP 3: Run this ***
CREATE WAREHOUSE IF NOT EXISTS HACKATHON_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- *** STEP 4: Run these 3 lines together ***
USE DATABASE HACKATHON;
USE SCHEMA DATA;
USE WAREHOUSE HACKATHON_WH;

-- *** STEP 5: Run all CREATE TABLE statements below together ***

CREATE OR REPLACE TABLE HACKATHON.DATA.HR_ATTRITION (
    EMPLOYEE_ID STRING,
    EMPLOYEE_NAME STRING,
    DEPARTMENT STRING,
    MANAGER_ID STRING,
    TENURE_YEARS FLOAT,
    PERFORMANCE_RATING INT,
    SALARY_BAND STRING,
    MONTHS_SINCE_PROMOTION INT,
    ENGAGEMENT_SCORE FLOAT,
    TEAM_SIZE INT,
    HIRE_DATE DATE,
    ATTRITION_RISK_LABEL STRING
);

CREATE OR REPLACE TABLE HACKATHON.DATA.USER_ADOPTION (
    USER_ID STRING,
    TEAM STRING,
    ORG_UNIT STRING,
    FIRST_LOGIN_DATE DATE,
    LAST_ACTIVE_DATE DATE,
    TOTAL_SESSIONS INT,
    TOTAL_ACTIONS INT,
    STATUS STRING
);

CREATE OR REPLACE TABLE HACKATHON.DATA.CONTRACT_METADATA (
    CONTRACT_ID STRING,
    VENDOR_NAME STRING,
    CATEGORY STRING,
    CONTRACT_VALUE_USD FLOAT,
    START_DATE DATE,
    END_DATE DATE,
    GOVERNING_LAW STRING,
    LIABILITY_CAP_USD FLOAT,
    AUTO_RENEWS STRING,
    RISK_FLAGS STRING,
    RISK_LEVEL STRING,
    OWNER_TEAM STRING
);

CREATE OR REPLACE TABLE HACKATHON.DATA.ACCESS_LOGS (
    USER_ID STRING,
    ROLE STRING,
    TABLE_NAME STRING,
    TABLE_OWNER STRING,
    LAST_ACCESSED_DATE DATE,
    QUERY_COUNT_30D INT
);

CREATE OR REPLACE TABLE HACKATHON.DATA.ENGAGEMENT_LOGS (
    USER_ID STRING,
    TEAM STRING,
    ORG_UNIT STRING,
    WEEK_START DATE,
    CATEGORY STRING,
    SESSION_COUNT INT,
    ENGAGEMENT_SCORE FLOAT
);

-- *** STEP 6: Verify tables were created ***
SHOW TABLES IN SCHEMA HACKATHON.DATA;

-- ============================================================
-- NEXT: Upload CSVs
-- 1. Click "Data" in left sidebar > "Add Data" > "Load data into a Table"
-- 2. Select database: HACKATHON, schema: DATA
-- 3. Upload each CSV into its matching table:
--    hr_attrition.csv       → HR_ATTRITION
--    user_adoption.csv      → USER_ADOPTION
--    contract_metadata.csv  → CONTRACT_METADATA
--    access_logs.csv        → ACCESS_LOGS
--    engagement_logs.csv    → ENGAGEMENT_LOGS
-- ============================================================

-- *** STEP 7: Run AFTER uploading all CSVs to verify row counts ***
SELECT 'HR_ATTRITION' AS TBL, COUNT(*) AS ROW_COUNT FROM HACKATHON.DATA.HR_ATTRITION
UNION ALL SELECT 'USER_ADOPTION', COUNT(*) FROM HACKATHON.DATA.USER_ADOPTION
UNION ALL SELECT 'CONTRACT_METADATA', COUNT(*) FROM HACKATHON.DATA.CONTRACT_METADATA
UNION ALL SELECT 'ACCESS_LOGS', COUNT(*) FROM HACKATHON.DATA.ACCESS_LOGS
UNION ALL SELECT 'ENGAGEMENT_LOGS', COUNT(*) FROM HACKATHON.DATA.ENGAGEMENT_LOGS;
